version: '2'

services:
  blog:
    image: celavi/mojo-blog:latest
    restart: always
    ports:
      - '8080'
    volumes:
      - ./etc/blog.conf:/opt/app/etc/blog.conf
    depends_on:
      - db

  db:
    image: postgres:9.6.11
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: s3cret
