apiVersion: v1
kind: Service
metadata:
  name: db-{{ include "mojo-blog.fullname" . }}
  labels:
    app.kubernetes.io/name: db-{{ include "mojo-blog.name" . }}
    helm.sh/chart: {{ include "mojo-blog.chart" . }}
    app.kubernetes.io/instance: db-{{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app.kubernetes.io/name: db-{{ include "mojo-blog.name" . }}
    app.kubernetes.io/instance: db-{{ .Release.Name }}
