apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mojo-blog.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mojo-blog.name" . }}
    helm.sh/chart: {{ include "mojo-blog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mojo-blog.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mojo-blog.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            timeoutSeconds: 5
            initialDelaySeconds: 30
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 30
            httpGet:
              path: /
              port: 8080
          volumeMounts:
            - mountPath: /opt/app/etc
              name: blog-conf
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: blog-conf
        configMap:
            name: {{ template "mojo-blog.name" . }}-configuration
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
