name: CI - Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build --file ./examples/blog/Dockerfile --tag mojo-blog:$(date +%s) ./examples/blog
