name: CI - Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build --file ./examples/blog/Dockerfile --tag mojo-blog:latest ./examples/blog

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests inside the Docker container
        run: docker run --rm -v ./examples/blog/t:/opt/app/t mojo-blog:latest carton exec prove -lr -j4
